//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VANHACK_Forum_Project.Pages {
    
    
    public partial class Add_Category_Post {
        
        /// <summary>
        /// UC_Add_Post1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VANHACK_Forum_Project.UserControl.UC_Add_Post UC_Add_Post1;
    }
}
